[package]
name = "classical_sim"
version = "0.1.0"
edition = "2024"
 
[dependencies]
periodic_array_2d = {path = "../periodic_array_2d" }
monte_carlo       = {path = "../monte_carlo" }

rand = "0.9.0"